### ISSUE TITLE
property文件在哪里啊

### ISSUE THREAD

**Issue by Deill2** [artintel/LearningCode#1]

**Comment by Deill2** [comment]
> _No description provided._

**Comment by Deill2** [comment]
知道了，property就是自己建一个文件叫property，给上参数numclass，size,size

**Comment by artintel** [comment]
啊对。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月6日(周五) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)




 
知道了，property就是自己建一个文件叫property，给上参数numclass，size,size

**Comment by artintel** [comment]
好像inaightface的原作者集成了pytorch，你要不要去看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月6日(周五) 晚上9:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)




 
知道了，property就是自己建一个文件叫property，给上参数numclass，size,size

**Comment by Deill2** [comment]
请问是这个么https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch，我看论文中提到了这个。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 上午10:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)





 好像inaightface的原作者集成了pytorch，你要不要去看看 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2022年5月6日(周五) 晚上9:43 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;; 
 主题: Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1) 
 
 
 
 
   
 知道了，property就是自己建一个文件叫property，给上参数numclass，size,size

**Comment by artintel** [comment]
对 是这个




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 上午10:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)





 请问是这个么https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch，我看论文中提到了这个。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月7日(星期六) 上午10:20 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1) 
 
 
 
 
 
  好像inaightface的原作者集成了pytorch，你要不要去看看  
   
   
   
  ---原始邮件---  
  发件人: ***@***.***&amp;amp;gt;  
  发送时间: 2022年5月6日(周五) 晚上9:43  
  收件人: ***@***.***&amp;amp;gt;;  
  抄送: ***@***.***&amp;amp;gt;;  
  主题: Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)  
   
   
   
   
     
  知道了，property就是自己建一个文件叫property，给上参数numclass，size,size

**Comment by Deill2** [comment]
他这个也需要你的代码才能训练自己的数据集，他的readme没有提怎么制作自己的数据集。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 上午10:33
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)





 对 是这个 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年5月7日(星期六) 上午10:32 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1) 
 
 
 
 
 
  请问是这个么https://github.com/deepinsight/insightface/tree/master/recognition/arcface_torch，我看论文中提到了这个。  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "artintel/LearningCode"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2022年5月7日(星期六) 上午10:20  
  ***@***.***&amp;amp;gt;;  
  ***@***.***&amp;amp;gt;;"State ***@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)  
   
   
   
   
   
   好像inaightface的原作者集成了pytorch，你要不要去看看   
     
     
     
   ---原始邮件---   
   发件人: ***@***.***&amp;amp;amp;gt;   
   发送时间: 2022年5月6日(周五) 晚上9:43   
   收件人: ***@***.***&amp;amp;amp;gt;;   
   抄送: ***@***.***&amp;amp;amp;gt;;   
   主题: Re: [artintel/LearningCode] property文件在哪里啊 (Issue #1)   
     
     
     
     
       
   知道了，property就是自己建一个文件叫property，给上参数numclass，size,size
